### ISSUE TITLE
AuthCode串应用的问题

### ISSUE THREAD

**Issue by ly123567** [Jie2GG/Native#1]
当两个文件结构相类似的、同时使用该SDK编写的插件在同一个CoolQ上运行的时候，日志中显示的应用名会混乱(即无论应用A还是应用B处理的消息会显示为应用A发出的，但在重启之前显示的发出应用一定相同)。
同时，如果将“日志中的发出应用”禁用掉(如应用A)，那么应用B的应答也会失效。

以下贴子中最新版本是使用本SDK编写的：
[实际应用A](https://cqp.cc/t/38619)  [实际应用B](https://cqp.cc/t/40464)
实际应用A代码(Github)：[点此](https://github.com/ly123567/CQP-LiveSignForDouyu)
应用B除了部分变量外基本结构与A相同。

PS：其实如果我刚开始没有把Native.Demo/App.Event/SQLiteManager.cs中的数据库地址(path)用常量写死，而是采用EnApi.Instance.GetAppDirectory()的话，甚至连数据库都会串Orz。。。

据开发者群dalao讲应当是AuthCode没有处理好的问题。。。

**Comment by Jie2GG** [comment]
感谢反馈. 正在就此问题进行查找分析.

**Comment by Jie2GG** [comment]
> 当两个文件结构相类似的、同时使用该SDK编写的插件在同一个CoolQ上运行的时候，日志中显示的应用名会混乱(即无论应用A还是应用B处理的消息会显示为应用A发出的，但在重启之前显示的发出应用一定相同)。
> 同时，如果将“日志中的发出应用”禁用掉(如应用A)，那么应用B的应答也会失效。
> 
> 以下贴子中最新版本是使用本SDK编写的：
> [实际应用A](https://cqp.cc/t/38619) [实际应用B](https://cqp.cc/t/40464)
> 实际应用A代码(Github)：[点此](https://github.com/ly123567/CQP-LiveSignForDouyu)
> 应用B除了部分变量外基本结构与A相同。
> 
> PS：其实如果我刚开始没有把Native.Demo/App.Event/SQLiteManager.cs中的数据库地址(path)用常量写死，而是采用EnApi.Instance.GetAppDirectory()的话，甚至连数据库都会串Orz。。。
> 
> 据开发者群dalao讲应当是AuthCode没有处理好的问题。。。

感谢反馈!　目前已经大致确定了SDK导致AuthCode内存地址重叠的问题, 目前已尝试修复, 请开发者测试一下

**Comment by ly123567** [comment]
收到~晚些时候会着手测试。。。
