### ISSUE TITLE
好像没找到阻塞消息传递的API

### ISSUE THREAD

**Issue by redXpanda** [Jie2GG/Native#135]
处理消息后如何避免消息继续在CQ中传递？
避免一个消息被多个应用处理。

**Comment by gurasaa** [comment]
在各事件 : `` e.Handler = true;``
需要尽快於判断后设置，否则可能仍会传递

**Comment by Jie2GG** [comment]
感谢反馈.  各事件使用 e.Handler = true; 进行设置消息阻塞. 但是由于我的疏忽. 并未在底层处理此问题. 现在该问题已经在测试版中修复. 请等待更新. 感谢支持
