### ISSUE TITLE
第一次启动模块必无响应

### ISSUE THREAD

**Issue by redXpanda** [Jie2GG/Native#136]
编译后载入CQ，进入应用管理，启动模块，无响应，重新启动CQ后正常。
程序只有一个简单的复读机。
WINDOWS上面倒是还好，主要是在LINUX容器上部署的，出现这个问题挺烦人的。

**Comment by redXpanda** [comment]
补充一下，现在发现docker上会这样：点击启动模块，console报错：QA.exe: corruntimehost.c:1314：ReallyFixupVTable: 假设 ‘0’ 失败。
然后过一会应用恢复响应，告知发生错误(未知)（查log会看到这一句：api授权接收函数Initialize返回值非0(-121)）
重载应用或者重启CQ或者重启docker均无法解决问题。

**Comment by gurasaa** [comment]
請確保使用的鏡像具備dotnet45環境。
如是你是使用官方的鏡像，需要手動安裝。

**Comment by redXpanda** [comment]
明白了，应该是.net环境没装，忽略了这个。我去研究一下这个官方的镜像怎么装.net，对docker不熟。
