### ISSUE TITLE
获取好友列表报错

### ISSUE THREAD

**Issue by yeziQAQ** [Jie2GG/Native#148]
**在群消息发送好友,返回好友列表(e.CQApi.GetFriendList())。获取列表报以下错误**

发现未处理的异常!
System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: qqId
   在 Native.Csharp.Sdk.Cqp.Model.QQ..ctor(CQApi api, Int64 qqId) 位置 D:\Code\Native.Csharp.Frame-master\Native.Csharp.Frame-master\Native.Csharp.Sdk\Cqp\Model\QQ.cs:行号 50
   在 Native.Csharp.Sdk.Cqp.Model.FriendInfo..ctor(CQApi api, Byte[] cipherBytes) 位置 D:\Code\Native.Csharp.Frame-master\Native.Csharp.Frame-master\Native.Csharp.Sdk\Cqp\Model\FriendInfo.cs:行号 54
   在 Native.Csharp.Sdk.Cqp.CQApi.GetFriendList() 位置 D:\Code\Native.Csharp.Frame-master\Native.Csharp.Frame-master\Native.Csharp.Sdk\Cqp\CQApi.cs:行号 818
   在 com.apbenben.quote.Core.Event_GroupMessage.GroupMessage(Object sender, CQGroupMessageEventArgs e) 位置 D:\Code\Native.Csharp.Frame-master\Native.Csharp.Frame-master\com.apbenben.quote.Core\Event_GroupMessage.cs:行号 40
   在 Native.Csharp.App.Export.CQEventExport.Event_eventGroupMsg(Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, IntPtr msg, Int32 font)

[CQP.dll](0x10000000)->CQ_setFatal(0x10588)+0x27=0x100105AF
0x0BC54FDD
0x0BC54F56
[clr.dll](0x72240000)+0xF066=0x7224F066
[clr.dll](0x72240000)->LogHelp_TerminateOnAssert(0x119E0)+0x93A=0x7225231A
[clr.dll](0x72240000)+0x77CDB=0x722B7CDB
[clr.dll](0x72240000)+0x31CDF7=0x7255CDF7
[clr.dll](0x72240000)+0x383B63=0x725C3B63
[clr.dll](0x72240000)+0x383F30=0x725C3F30
[clr.dll](0x72240000)+0x30389E=0x7254389E
[clr.dll](0x72240000)+0x3036B9=0x725436B9
[clr.dll](0x72240000)+0x30304C=0x7254304C
[clr.dll](0x72240000)+0x31A08B=0x7255A08B
[clr.dll](0x72240000)+0x31951D=0x7255951D
[clr.dll](0x72240000)+0x319795=0x72559795
[mscoreei.dll](0x72B40000)->GetXMLElementAttribute(0x50650)+0x3077=0x72B936C7
[mscoreei.dll](0x72B40000)->GetXMLElementAttribute(0x50650)+0x2FC1=0x72B93611
[KERNELBASE.dll](0x758E0000)->UnhandledExceptionFilter(0x1AA010)+0x1CB=0x75A8A1DB
[ntdll.dll](0x771D0000)+0xA303E=0x7727303E
[ntdll.dll](0x771D0000)->RtlGetAppContainerNamedObjectPath(0x66540)+0xBD=0x772365FD

**Comment by Jie2GG** [comment]
该报错属于校验酷Q返回数据时报错, 若在生产环境中, 请切换为 Release 进行编译, 将异常抛出变成返回 null

**Comment by yeziQAQ** [comment]
好的
