### ISSUE TITLE
请教如何连接sqllite

### ISSUE THREAD

**Issue by ZGarry** [Jie2GG/Native#149]
遇到的问题，显示sqllite.DLL未加载
![image](https://user-images.githubusercontent.com/43488431/76336367-e03e9800-6330-11ea-9893-3c5e8b61b7eb.png)

尝试了两种方案引入tool下的sqllite：
1. 引入native.TOOLS项目
2. 先编译native.TOOLS，生成dll后引入，均失败

请求协助，不胜感激~

**Comment by Jie2GG** [comment]
感谢支持, 该 sqlite 基于的是 **酷Q** 中的 sqlite3.dll 请检查酷Q的 bin 目录是否存在 sqlite3.dll

**Comment by ZGarry** [comment]
好的，目前已经解决了。
1. 一开始我，为了检测sqllie是否可用，新建了一个控制台应用，引用tools工具，遇到此问题。
2.后直接在APPID.code程序集下链接sqllite数据库，均成功

**Comment by Jie2GG** [comment]
好的, 感谢你对 Native.Sdk 的支持
