### ISSUE TITLE
Wiki 里的 "10. IniConfig的使用" 需要更新

### ISSUE THREAD

**Issue by Matrixchung** [Jie2GG/Native#155]
经查阅源码和` IniConfig 类的 ReadMe 发现，Wiki 中的这一条栏目所提供的代码已经过时，需要更新。
```
IniObject iniFile = IniObject.LoadOrCreate ("test.ini");
// 方式一
// 判断是否存在 "节点1"
if (iniFile.ContainsKey ("节点1"))
{
    IniValue iniValue = iniFile["节点1"]["Username"];            // 获取 "Username" 的值, 返回的是 IniValue 对象
    string username = iniValue.Value;                           // 获取字符串
    bool isManager = iniFile["节点1"]["IsManager"].ToBoolean (); // 获取布尔值
    int level = -1;
    // 为了代码安全, 还可以判断是否存在键
    if (iniFile["节点1"].ContainsKey ("Level"))
    {
        level = iniFile["节点1"]["Level"].ToInt32 ();
    }
}

// 方式二
IniSection section1 = null;
if (iniFile.TryGetValue ("节点1", out section1))
{
    IniValue iniValue = null;
    if (section1.TryGetValue ("Username", out iniValue))
    {
        string username = iniValue.Value;
    }
    if (section1.TryGetValue ("IsManager", out iniValue))
    {
        bool isManager = iniValue.ToBoolean ();
    }
}
```

**Comment by Jie2GG** [comment]
该 Wiki 页将连同新版 IniConfig 同时上线.

**Comment by Jie2GG** [comment]
> 经查阅源码和` IniConfig 类的 ReadMe 发现，Wiki 中的这一条栏目所提供的代码已经过时，需要更新。
> 
> ```
> IniObject iniFile = IniObject.LoadOrCreate ("test.ini");
> // 方式一
> // 判断是否存在 "节点1"
> if (iniFile.ContainsKey ("节点1"))
> {
>     IniValue iniValue = iniFile["节点1"]["Username"];            // 获取 "Username" 的值, 返回的是 IniValue 对象
>     string username = iniValue.Value;                           // 获取字符串
>     bool isManager = iniFile["节点1"]["IsManager"].ToBoolean (); // 获取布尔值
>     int level = -1;
>     // 为了代码安全, 还可以判断是否存在键
>     if (iniFile["节点1"].ContainsKey ("Level"))
>     {
>         level = iniFile["节点1"]["Level"].ToInt32 ();
>     }
> }
> 
> // 方式二
> IniSection section1 = null;
> if (iniFile.TryGetValue ("节点1", out section1))
> {
>     IniValue iniValue = null;
>     if (section1.TryGetValue ("Username", out iniValue))
>     {
>         string username = iniValue.Value;
>     }
>     if (section1.TryGetValue ("IsManager", out iniValue))
>     {
>         bool isManager = iniValue.ToBoolean ();
>     }
> }
> ```

新版 IniConfig 与 在线文档均已上线. 请更新 SDK 后参考在线文档的例程使用

文档地址: https://native.run
