### ISSUE TITLE
建议迁移到.netcore

### ISSUE THREAD

**Issue by F-Unction** [Jie2GG/Native#156]
建议新开一个仓库放.netcore的SDK

**Comment by Jie2GG** [comment]
由于.Net Core 和 .Net Framework 在项目结构上有众多不同, 并且酷Q不是一个跨平台应用, .Net Core 的版本有待考量.

**Comment by F-Unction** [comment]
> 由于.Net Core 和 .Net Framework 在项目结构上有众多不同, 并且酷Q不是一个跨平台应用, .Net Core 的版本有待考量.

好的 谢谢
