### ISSUE TITLE
CQExport.tt无法运行

### ISSUE THREAD

**Issue by Metric-Void** [Jie2GG/Native#161]
> 自定义工具“TextTemplatingFileGenerator”与文件“Export\CQExport.tt”相关联，但在项目中找不到该自定义工具的输出。  你可以通过在解决方案资源管理器中右击该文件并选择“运行自定义工具”，尝试重新运行该自定义工具。

按照 [https://native.run/articles/01.html](https://native.run/articles/01.html) 做的。重复运行仍然是相同的结果。不管改没改appid都无法运行。

虽然CQEventExport.cs里的相关项目已经被更改了，但是指引页面上说的是
> 若在运行过程中, 没有发生任何错误与警告. 则表示 tt 文件编译正常. 至此 AppID 设置完成

所以想确认一下

VS Community 2019.

**Comment by Jie2GG** [comment]
TextTemplate 是 Visual Studio 自带的执行脚本之一. 
你需要做的事情:
1. 检查使用的是否为 Bland for Visual Studio
2. 检查使用的 Visual Studio 开发环境是否完整.

**Comment by Metric-Void** [comment]
谢谢提醒。更新+重置了一下Visual Studio，之后问题消失。
