### ISSUE TITLE
重载的等号操作符"==" NPE的问题

### ISSUE THREAD

**Issue by traceless0929** [Jie2GG/Native#165]
举例
`
public static bool operator == (QQ a, QQ b)
		{
			return a.Equals (b);
		}
`
当a是null的时候会报NPE导致插件报错，酷Q报出非法读取

**Comment by Jie2GG** [comment]
请附上详细的错误截图以及错误信息

**Comment by traceless0929** [comment]
![](https://gitee.com/DotNetTraceless/mydatadb/raw/master/img/20200527163307.png)
我们知道，这种方法可以通过 fromQQ!=null 来避免，但是如果fromQQ也是null 依旧会NPE
![](https://gitee.com/DotNetTraceless/mydatadb/raw/master/img/20200527163516.png)

**Comment by Jie2GG** [comment]
问题已修复, 感谢代码贡献
