### ISSUE TITLE
使用插件需要将插件原DLL放在酷Q根目录？

### ISSUE THREAD

**Issue by chuxiaaaa** [Jie2GG/Native#174]
这是BUG吗？被引用的插件DLL如果不放在根目录就会报错
System.TypeLoadException: 未能从程序集“app.chuxia.lolhk, Version=4.1.1.216, Culture=neutral, PublicKeyToken=null”中加载类

**Comment by Jie2GG** [comment]
可以放在bin目录下，但是还是请使用SDK自带的打包工具

**Comment by chuxiaaaa** [comment]
找到问题原因了，Native.Core的程序集名和插件项目的程序集同名，导致Costura打包判断程序集错乱，总体来说是本人命名没规范的问题。
