### ISSUE TITLE
关于V4.2.2.0501 release版API使用GroupMemberInfo.ToString()方法报错的问题及临时解决方案

### ISSUE THREAD

**Issue by Orideus** [Jie2GG/Native#175]
不知道现在git上面的版本修了这个问题没有，初步（未设置错误处理代码时）提示读取内存失败，使用try/catch抓到的问题是未将对象引用设置到对象的实例。
定位到问题主要在于性别的GetDescription方法不能正确返回描述，考虑到问题出在GetDescription方法，MemberType成员类型那里可能也会触发同样的bug。
我把GetDescription替换成ToString凑活了一下，勉强能用了。
顺便一提，最后一行（允许修改名片）后面的换行似乎可以删掉

**Comment by Jie2GG** [comment]
请附上详细的错误讯息. 以及调试的报错.

**Comment by Orideus** [comment]
![Error01](https://user-images.githubusercontent.com/57572809/84679575-07c28380-af64-11ea-8f87-d36a20d40746.png)
↑这是不处理异常时酷Q给出的错误提示，可能没什么用
![Error02](https://user-images.githubusercontent.com/57572809/84679577-098c4700-af64-11ea-812e-8356fcb443f7.png)
↑这是catch到的异常
异常处的代码分别是
DescriptionAttribute attribute = fieldInfo.GetCustomAttribute<DescriptionAttribute> (false);
builder.AppendFormat ("性别: {0}{1}", this.Sex.GetDescription(), Environment.NewLine);
e.FromGroup.SendGroupMessage(cacheInfo.ToString());

**Comment by Jie2GG** [comment]
该问题已修复.
